apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcName }}
  namespace: {{ .Values.nameSpace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.deploymentappName }}
  ports:
  - port: 80
    targetPort: 5000
