apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentappName }}
  namespace: {{ .Values.nameSpace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.deploymentappName }}
      type: backend
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentappName }}
        type: backend
    spec:
      containers:
      - name: {{ .Values.deploymentappName }}
        image: applesama/ordersystem:2.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: {{ .Values.deploymentconfigMap.configMapRef.name }}
        - secretRef:
            name: {{ .Values.deploymentSecret.secretRef.name }}
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh','-c','until nslookup {{ .Values.postgresqlsvcName }}.{{ .Values.nameSpace }}.svc.cluster.local; do echo waiting for DB; sleep 5; done;']
