apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deploymentSecret.secretRef.name }}
  namespace: {{ .Values.nameSpace }}
type: Opaque
data:
  DB_URL: {{ .Values.deploymentSecret.data.DB_URL }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deploymentconfigMap.configMapRef.name }}
  namespace: {{ .Values.nameSpace }}
data:
  FLASK_APP: {{ .Values.deploymentconfigMap.data.FLASK_APP}}
  FLASK_ENV: {{ .Values.deploymentconfigMap.data.FLASK_ENV}}
  APP_VERSION: {{ .Values.deploymentconfigMap.data.App_VERSION}}

