kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.pvName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/bitnami/postgresql/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvcName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi