apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresqlsvcName }}
  namespace: {{ .Values.nameSpace }}
spec:
  selector:
    app: {{ .Values.postgresqlappName }}
  ports:
  - port: 5432
    targetPort: 5432
