FROM postgres:13.3

# Set the environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=0000
ENV POSTGRES_DB=postgres

# Copy the initialization SQL script to the container


# Expose the PostgreSQL port
EXPOSE 5432


