nameSpace: order-prod

deploymentappName: order-flask-prod

postgresqlappName: postgresql-db-prod

postgresqlsvcName: postgresql-svc

deploymentImage:
  name: applesama/ordersystem
  tag: :2.0

svcName: backend-svc-prod

pvName: postgres-pv-prod

pvcName: postgres-pvc-prod

orderappHpa: orderapp-hpa-prod

postgresSecret:
  name: postgres-sc
  data: 
    POSTGRES_PASSWORD: MDAwMA==
    POSTGRES_USER: cG9zdGdyZXM=

postgresconfigMap:
  name: postgres-config
  data: 
    POSTGRES_DB: postgres

postgresImage:
  name: bitnami/postgresql
  tag: 13

deploymentSecret:
  secretRef:
    name: backend-sc
  data:
    DB_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Bvc3RncmVzOjAwMDBAcG9zdGdyZXNxbC1zdmM6NTQzMi9wb3N0Z3Jlcw==

deploymentconfigMap:
  data: 
    FLASK_APP: app
    FLASK_ENV: development
    APP_VERSION: v0.1.0
  configMapRef:
    name: backend-config